language:        node_js
sudo:            required
dist: trusty
os:
  - linux
node_js:
  - "11.9.0"

script:
- travis_retry npm install --silent
- npm run lint
- npm run test
- npm run test:performance